
### link to retrieve all books 
http://localhost:4000/api/books

###link to retrieve book by ID
http://localhost:4000/api/books/64931c25bdd7496b3c4800c3


###link to create book 
POST  http://localhost:4000/api/books/ HTTP/1.1

###Deployment link on render
https://library-management-api-n823.onrender.com/api/books


### Google OAuth
http://localhost:4000/auth/google